scss_files: 'src/Frontend/styles/*.scss'

exclude:
  - 'vendor/**/*.scss'
  - 'vendor/**/*.css'
  - 'node_modules/**/*.scss'
  - 'node_modules/**/*.css'

linters:
  Comment:
    allowed: '^[/* ]* \(c\)'
