language: php
php:
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7

install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS sententiaregum;"
  - mysql -e "CREATE DATABASE IF NOT EXISTS sententiaregum_dev;"
  - echo "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev';" | mysql -u root
  - echo "GRANT ALL PRIVILEGES ON * . * TO 'dev'@'localhost';" | mysql -u root
  - echo "FLUSH PRIVILEGES;" | mysql -u root
  - gem install sass
  - npm install -g karma-cli webpack node-sass
  - composer install
  - php app/check.php
  - php app/console security:check

script:
  - bin/phpunit -c app
  - karma start --single-run
