language: php
php:
  - 5.6
  - 7
  - hhvm

sudo: false

services:
  - redis-server

# execution matrix
matrix:
  allow_failures:
    - php: hhvm
    - php: 7

# composer cache for faster install process and less issues with github api
cache:
  directories:
    - $HOME/.composer/cache/files

# prepare travis ci for the build process
install: ./travis-ci/scripts/install.sh

# linters
before_script: ./travis-ci/scripts/lint.sh

# execute tests
script: ./travis-ci/scripts/tests.sh
