language: php
php:
  - 5.6
  - 7
  - hhvm

services:
  - redis-server

# execution matrix
matrix:
  allow_failures:
    - php: hhvm
    - php: 7

# composer cache for faster install process and less issues with github api
cache:
  directories:
    - $HOME/.composer/cache/files

# prepare travis ci for the build process
install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS sententiaregum;"
  - mysql -e "CREATE DATABASE IF NOT EXISTS behat;"
  - echo "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev';" | mysql -u root
  - echo "GRANT ALL PRIVILEGES ON * . * TO 'dev'@'localhost';" | mysql -u root
  - echo "FLUSH PRIVILEGES;" | mysql -u root
  - npm install -g mocha webpack node-sass eslint eslint-plugin-react less
  - cp travis-ci/travis_parameters.yml app/config/parameters.yml
  - composer install
  - php app/check.php

# linters
before_script:
  - npm run lint
  - php app/console security:check
  - php app/console lint:yaml app/config
  - php app/console lint:yaml .scrutinizer.yml
  - php app/console lint:yaml .travis.yml
  - php app/console lint:yaml .sensiolabs.yml
  - php app/console lint:yaml behat.yml.dist
  - php app/console lint:twig src
  - php app/console lint:twig app
  - php app/console doctrine:schema:validate

# execute tests
script:
  - bin/behat --strict -f progress --no-snippets
  - bin/phpunit -c app
  - npm test
