services:
  app.repository.user:
    class: AppBundle\Model\User\UserRepository
    tags:
      - { name: app.tag.repository, entity: Account:User }
    public: false
  app.repository.role:
    class: Doctrine\ORM\EntityRepository
    tags:
      - { name: app.tag.repository, entity: Account:Role }
    public: false
