services:
  app.validator.locale:
    class: AppBundle\Validator\Constraints\LocaleValidator
    arguments:
      - "%app.locale_keys%"
    tags:
      - { name: validator.constraint_validator, alias: "app.validator.locale" }
  app.validator.unique_property:
    class: AppBundle\Validator\Constraints\UniquePropertyValidator
    arguments:
      - "@doctrine"
    tags:
      - { name: validator.constraint_validator, alias: "app.validator.unique_property" }
  app.validator.recaptcha_key:
    class: AppBundle\Validator\Constraints\RecaptchaValidator
    arguments:
      - "@app.recaptcha_validator"
      - "%site_url%"
    tags:
      - { name: validator.constraint_validator, alias: "app.validator.recaptcha_key" }